### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1419: ordinal not in range(128)

### ISSUE THREAD

**Issue by E-v-Es** [homeisfar/LinuxDir2HTML#10]
I am testing linuxdir2HTML in Red Hat Enterprise Linux Server release 7.9 (Maipo). RHEL 7.9 comes with Python 3.6.8 (meaning it receives security fixes but no release upgrades).

`$ linxdir2html / out-file
12:26:42 Root index directory: [/]
Traceback (most recent call last):
  File ".local/bin/linuxdir2html", line 11, in <module>
    sys.exit(main())
  File "/root/.local/lib/python3.6/site-packages/linuxdir2html/linuxdir2html.py", line 111, in main
    total_numFiles, total_numDirs, grand_total_size, file_links
  File "/root/.local/lib/python3.6/site-packages/linuxdir2html/linuxdir2html.py", line 229, in generateHTML
    for line in template_file:
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1419: ordinal not in range(128)`

After some testing it seems it fails on line 1722 in template.html:
`<input type="search" id="search_text" title="Search Box"> <div onclick="javascript:alert('Search Tips:\n\nUse * and ? as wildcards. * matches zero or more characters, ? matches exactly one character.\n\nPrefix your search with &gt; to search only the current folder or &gt;&gt; to search the current folder and sub folders.');" class="app_header_search_help">?</div>`

Changing:
`template_file = open((Path(__file__).parent / 'template.html'), 'r')`
into:
`template_file = open((Path(__file__).parent / 'template.html'), 'r', encoding="utf-8")`
solved the issue for me.

Making changes for older Python versions might not be first priority, but the overall idea of opening the template file in utf-8 encoding might not be bad in general.

**Comment by homeisfar** [comment]
Thanks for catching this. It's an oversight to not load the template file in utf8 encoding.
