### ISSUE TITLE
Double quotes in file names break the HTML

### ISSUE THREAD

**Issue by lazypete365** [homeisfar/LinuxDir2HTML#5]
Hello,

Running LinuxDir2HTML on my server, I have noticed that when I try to make a listing of certain directories the html file got stuck in "Loading...". Debugging with the browser led pretty quickly to files and directories with names containing double quotes ("), which break the syntax so that the page never loads.

Fiddling a bit with the code, I tried escaping double quotes in `generateDirArray` like so:
 
```
        current_dir_escaped=current_dir.replace('"','\\"')
        arr.append(f'{current_dir_escaped}*0*{dir_mod_time}')
```

```
                 file_escaped=file.replace('"','\\"')
                 arr.append(f'{file_escaped}*{file_size}*{mod_time}')
``` 

Not sure if there is any more filename weirdness that can break the html, but this seemed to do the trick for me without breaking anything else in the process.

**Comment by prestidigitonium** [comment]
> Hello,
> 
> Running LinuxDir2HTML on my server, I have noticed that when I try to make a listing of certain directories the html file got stuck in "Loading...". Debugging with the browser led pretty quickly to files and directories with names containing double quotes ("), which break the syntax so that the page never loads.
> 
> Fiddling a bit with the code, I tried escaping double quotes in `generateDirArray` like so:
> 
> ```
>         current_dir_escaped=current_dir.replace('"','\\"')
>         arr.append(f'{current_dir_escaped}*0*{dir_mod_time}')
> ```
> 
> ```
>                  file_escaped=file.replace('"','\\"')
>                  arr.append(f'{file_escaped}*{file_size}*{mod_time}')
> ```
> 
> Not sure if there is any more filename weirdness that can break the html, but this seemed to do the trick for me without breaking anything else in the process.

Can you tell me a way to apply your fix? I installed LinuxDir2HTML from pip in archlinux. I suppose I need to remove it and manually download this github version. Where should I place the fix?

**Comment by homeisfar** [comment]
Fixed in the latest release.
